MODEL:
  architecture:  "TSViT"
  img_res: 24
  max_seq_len: 16  #
  num_channels: 11
  num_features: 16
  num_classes: 6
  ignore_background: True
  dropout: 0.
  patch_size: 2
  dim: 128
  temporal_depth: 4
  spatial_depth: 4
  heads: 4
  pool: 'cls'
  dim_head: 64
  emb_dropout: 0.
  scale_dim: 4
  SE_reduction: 6

DATASETS:
  src:
    train:
      dataset: "MTLCC"
      max_seq_len: 16
      batch_size: 32
      extra_data:
      num_workers: 4
    eval:
      dataset: "MTLCC"
      max_seq_len: 16
      batch_size: 32
      extra_data:
      num_workers: 4
  trg:
    train:
      dataset: "PASTIS24_fold1"
      max_seq_len: 16
      batch_size: 32
      extra_data:
      num_workers: 4
    eval:
      dataset: "PASTIS24_fold1"
      max_seq_len: 16
      batch_size: 32
      extra_data:
      num_workers: 4

SOLVER:
  num_epochs: 200
  num_warmup_epochs: 10
  steps: (0, 80000)
  loss_function:  masked_cross_entropy

  loss_function_da:  mk-mmd
  loss_lambda_mmd: 0.5
  mmd_kernel_mul: 2.0
  mmd_kernel_num: 5
  mmd_fix_sigma: null
  alpha_sum: 1.0

  class_weights:
  lr_scheduler: 'cosine'
  lr_base: 1e-3
  lr_min: 5e-4
  lr_start: 1e-8
  num_cycles: 1
  reset_lr: True   # resets lr to base value when loading pretrained model
  weight_decay: 0.000

CHECKPOINT:
  load_from_checkpoint:
  partial_restore: False
  save_epoch_interval: 2
  save_path: 'models/saved_models/MTLCC/TSViT'
  train_metrics_steps: 250
  eval_steps: 2000
  save_steps: 1000000
